version: '2'
services:
    dragon_console-app:
        image: dragon_console
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dragon_console-mysql:3306/dragon_console?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dragon_console-mysql:
        extends:
            file: mysql.yml
            service: dragon_console-mysql
